name: Hello World

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        description: 'Où déployer ?'
        required: true
        type: choice
        options:
          - staging
          - production

jobs:
  hello:
    runs-on: ubuntu-24.04
    steps:
      - name: Dire bonjour
        run: echo "Hello, GitHub Actions!"

      - name: Afficher des infos sur le contexte
        run: |
          echo "Repository: \${{ github.repository }}"
          echo "Branche: \${{ github.ref_name }}"
          echo "Auteur du commit: \${{ github.actor }}"
          echo "Test echo secrets: ${{ secrets.COUCOU_SECRET }}"
          echo "Test echo secrets: ${{ vars.VARIBLE_TEST }}"
